services:
  - type: web
    name: qrcraft
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:generate
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
